mysql:
  build: ./mysql
  ports:
    - "3306:3306"
  volumes:
    - ./mysql/my.cnf:/etc/mysql/my.cnf
    - ./mysql/data:/var/lib/mysql
    - /etc/localtime:/etc/localtime
  environment:
    - MYSQL_ROOT_PASSWORD=your_mysql_password
nodejs:
  build: ./nodejs
  ports:
    - "3000:3000"
  volumes:
    - ./app:/usr/share/nginx/html
    - /etc/localtime:/etc/localtime
  links:
    - mysql:mysql
nginx:
  build: ./nginx
  ports:
    - "80:80"
    - "443:443"
    - "8080:80"
  volumes:
    - ./app:/usr/share/nginx/html
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
    - ./nginx/ca/server.crt/:/etc/nginx/server.crt:ro
    - ./nginx/ca/server.key/:/etc/nginx/server.key:ro
    - /etc/localtime:/etc/localtime
  links:
    - nodejs:__DOCKER_NODEJS__
